name: godev

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      -
        name: Call pkg.go.dev
        uses: docker/bake-action@v1
        with:
          targets: godev
